micronaut:
   application:
      name: hc-programm-selector
# Message Bus configuration - DEV Enviroment
rabbitmq:
   host: 192.168.2.118
   port: 5672
# Programm configuration
hc3:
   temperature-queue:
      name: hc-temperature
   sensor:
      combustion: 22-000000336328
      leading-line: 22-000000337836
      return-line: 22-000000337836
      buffer: 22-000000337836
      garage: 22-000000337836
   pump:
      garage:
         gpio-id: 22
      heating:
         gpio-id: 12
         switch-on-temp: 45
   ssh:
      username: pi
      password: raspberry
      host: 192.168.2.118
      
      
      